#!/bin/bash

# 4) Script: Find biggest number in 3 numbers - if -elif block

NUM1="$((3))"
NUM2="$((1))"
NUM3="$((7))"

echo "Script to find biggest number from : $NUM1 , $NUM2, $NUM3"

if ["$NUM1" \> "$NUM2"]; then
	if ["$NUM1" \> "$NUM3"];
	then echo "$NUM1 is the biggest number"
	fi

elif ["$NUM2" \> "$NUM3"]; then 
echo "$NUM2 is the biggest number"

else echo "$NUM3 is the biggest number"

fi

